(define (get-min x y)
  (cond ((> x y) y)
        ((= x y) y)
        ((< x y) x)))
(define (get-max x y)
  (cond ((> x y) x)
        ((= x y) x)
        ((< x y) y)))
(define (sum-of-squares-of-top-two x y z)
  (define first-number (get-max x y))
  (define min-number (get-min x y))
  (define second-number (get-max min-number z))
  (define (square x) (* x x))
  (+ (square first-number) (square second-number)))
